extends: airbnb
parserOptions:
  ecmaVersion: 6
env:
  node: true
  mocha: true
rules:
  comma-dangle: 'off'
  import/no-extraneous-dependencies: 'off'
  strict: 'off'
  max-len: ['error', 140, 2, {
      ignoreUrls: true,
      ignoreComments: false,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
    }]


